package com.huawei.openalliance.ad.download.app;

/* JADX INFO: loaded from: classes6.dex */
public enum AppStatusV1 {
    FIRST_CLICK_BUTTON,
    PRE_CHECK_SUCCESS,
    PRE_CHECK_FAILED,
    WAITING_FOR_WIFI,
    WAITING,
    START_DOWNLOAD,
    RETRY_DOWNLOAD,
    CANCEL_DOWNLOAD,
    USER_PAUSE,
    PAUSE,
    USER_RESUME,
    RESUME,
    DOWNLOAD_SUCCESS,
    DOWNLOAD_FAILED,
    START_INSTALL,
    INSTALLER_INIT_FAILED,
    INSTALL_SUCCESS,
    INSTALL_FAILED,
    RETRY_INSTALL
}
