package com.huawei.hms.hihealth;

import com.huawei.hms.common.api.CommonStatusCodes;
import java.util.HashMap;

/* JADX INFO: loaded from: classes5.dex */
public class HiHealthStatusCodes extends CommonStatusCodes {
    public static final int ACTIVITY_RECORD_ENDED_ERROR = 50009;
    public static final int ACTIVITY_RECORD_TIMESTAMPS_ERROR = 50020;
    public static final int ACTIVITY_SUMMARY_DATATYPE_NOT_SUPPORT = 50057;
    public static final int AGGREGATION_DATA_TYPE_NOT_ALLOWED = 50027;
    public static final int API_EXCEPTION_ERROR = 50011;
    public static final int API_FLOW_LIMIT = 50067;
    public static final int API_FUNCTION_UNAVAILABLE = 50032;
    public static final int APPLICATION_NOT_FORGROUND = 50062;
    public static final int APP_ALREADY_IN_WORKOUT = 50300;
    public static final int APP_HEALTH_NOT_INSTALLED = 50033;
    public static final int APP_HEALTH_NOT_MATCH = 50034;
    public static final int APP_MISMATCH_ERROR = 50004;
    public static final int APP_NOT_ENABLED_ERROR = 50010;
    public static final int BLUETOOTH_FORBIDDEN_ERROR = 50014;
    public static final int CALL_POWER_KIT_ERROR = 50301;
    public static final int CANCEL_SELECT_DEVICE = 50307;
    public static final int DATA_FIELD_MUST_FILLED = 50028;
    public static final int DATA_IS_TOO_LARGE = 50025;
    public static final int DATA_MIGRATION_ING = 50043;
    public static final int DEVICES_NOT_SUPPORT = 50053;
    public static final int DEVICE_NOT_BIND = 50305;
    public static final int DEVICE_NOT_SUPPORT = 50060;
    public static final int DICT_PARSE_ERROR = 50052;
    public static final int DISABLE_DATA_OPERATION = 50061;
    public static final int DUPLICATED_DATA_TYPE_ERROR = 50001;
    public static final int ERROR_APP_PACKAGE_NAME = 50041;
    public static final int EXISTED_RECORDER_ERROR = -50001;
    public static final int GET_HISTORY_PERMISSIONS_FAIL = 50066;
    public static final int HEALTH_APP_INVALID_PACKAGENAME = 50039;
    public static final int HEALTH_APP_NOT_AUTHORISED = 50037;
    public static final int HEALTH_APP_NOT_ENABLED = 50064;
    public static final int HEALTH_RECORDS_NOT_EXIST = 50050;
    public static final int HEALTH_RECORDS_NOT_SUPPORT = 50051;
    public static final int HISTORY_PERMISSIONS_INSUFFCIENT = 50065;
    public static final int HMS_CORE_VER_NOT_MATCH = 50063;
    public static final int HUAWEIID_NOT_LOGGED_IN = 50045;
    public static final int HUAWEI_ID_SIGNIN_ERROR = 50047;
    public static final int INPUT_PARAM_MISSING = 50031;
    public static final int INTERFACE_NOT_SUPPORT_IN_REGION = 50058;
    public static final int INVALID_ACTIVITY_TYPE_IN_ACTIVITY_RECORD = 50054;
    public static final int INVALID_CONTEXT = 50049;
    public static final int JS_API_EXCEPTION_ERROR = 50055;
    public static final int JS_API_PARAM_ERROR = 50056;
    public static final int LISTENER_ALREADY_EXIST = 50035;
    public static final int LISTENER_NOT_EXIST = 50036;
    public static final int MISMATCH_DATA_TYPE_ERROR = 50002;
    public static final int MISMATCH_PACKAGE_NAME_ERROR = 50015;
    public static final int MISS_MUST_DATA_TYPE = 50302;
    public static final int NEED_APP_TRUSTLIST_ERROR = 50024;
    public static final int NONEXISTENT_DATA_COLLECTOR_ERROR = 50018;
    public static final int NON_HEALTH_USER = 50038;
    public static final int NOT_EXIST_DATA_TYPE_ERROR = 50003;
    public static final int NO_ACTIVITY_PERMISSION = 50042;
    public static final int NO_ACTIVITY_START = 50304;
    public static final int NO_AUTHORITY_ERROR = 50000;
    public static final int NO_BLE_PERMISSION_ERROR = 50006;
    public static final int NO_DATA_COLLECTOR_ERROR = -50000;
    public static final int NO_MONITOR_ERROR = -50003;
    public static final int NO_NETWORK = 50030;
    public static final int NO_REQUIRED_PERMISSION = 50046;
    public static final int NO_SAVED_DEVICE_ERROR = -50002;
    public static final int POLYMERIZED_NOT_SUPPORTED_ERROR = 50012;
    public static final int QUERY_TIME_EXCEED_LIMIT = 50059;
    public static final int READ_LATEST_NOT_SUPPORTED_ERROR = 50044;
    public static final int RECORD_NOT_SUPPORT_DATA_TYPE = 50303;
    public static final int SAMPLE_SET_TIMESTAMP_ERROR = 50019;
    public static final int SPORT_DEVICE_ERROR = 50306;
    public static final int START_SPORT_TIME_OUT = 50308;
    public static final int SYSTEM_VERSION_IS_INVALID = 50026;
    public static final int TRY_AGAIN_ERROR = 50008;
    public static final int UNKNOWN_AUTH_ERROR = 50005;
    public static final int UNSUPPORTED_ACCOUNT_ERROR = 50013;
    public static final int UNSUPPORTED_DATA_TYPE_ERROR = 50023;
    public static final int UNSUPPORTED_PLATFORM_ERROR = 50007;
    public static final int UNTRUST_COUNTRY_CODE = 50040;
    public static final int UNUSED_DATA_TYPE_NOT_ALLOWED = 50029;
    public static final int USELESS_SAMPLE_POINT_ERROR = 50021;
    public static final int USELESS_TIMESTAMP_ERROR = 50022;
    public static final int USER_OF_BETA_APP_EXCEED_RANGE = 50048;
    public static final int WORK_OUT_BE_OCCUPIED = 51001;
    public static final int WORK_OUT_TIME_OUT = 51000;
    private static final HashMap<Integer, String> aab;

    public static String getStatusCodeMessage(int i) {
        HashMap<Integer, String> map = aab;
        return map.containsKey(Integer.valueOf(i)) ? map.get(Integer.valueOf(i)) : CommonStatusCodes.getStatusCodeString(i);
    }

    static {
        HashMap<Integer, String> map = new HashMap<>();
        aab = map;
        map.put(Integer.valueOf(NO_DATA_COLLECTOR_ERROR), "Success with no data collector");
        map.put(Integer.valueOf(EXISTED_RECORDER_ERROR), "Success with already recorded");
        map.put(Integer.valueOf(NO_SAVED_DEVICE_ERROR), "Success with no saved device");
        map.put(Integer.valueOf(NO_MONITOR_ERROR), "Success with monitor not registered for fitness data updates");
        map.put(50000, "Application requires user authorization");
        map.put(50001, "The data type already exists");
        map.put(Integer.valueOf(MISMATCH_DATA_TYPE_ERROR), "Data type does not match package name");
        map.put(Integer.valueOf(NOT_EXIST_DATA_TYPE_ERROR), "Data type not exist");
        map.put(Integer.valueOf(APP_MISMATCH_ERROR), "App mismatch");
        map.put(Integer.valueOf(UNKNOWN_AUTH_ERROR), "Unknown authorization error");
        map.put(Integer.valueOf(NO_BLE_PERMISSION_ERROR), "Missing ble device permission");
        map.put(Integer.valueOf(UNSUPPORTED_PLATFORM_ERROR), "Unsupported platform");
        map.put(Integer.valueOf(TRY_AGAIN_ERROR), "Temporary error");
        map.put(Integer.valueOf(ACTIVITY_RECORD_ENDED_ERROR), "The activity record already has an end time");
        map.put(Integer.valueOf(APP_NOT_ENABLED_ERROR), "Application not enabled");
        map.put(Integer.valueOf(API_EXCEPTION_ERROR), "Api exception, please retry later");
        map.put(Integer.valueOf(POLYMERIZED_NOT_SUPPORTED_ERROR), "Polymerize not supported");
        map.put(Integer.valueOf(UNSUPPORTED_ACCOUNT_ERROR), "Unsupported account");
        map.put(Integer.valueOf(BLUETOOTH_FORBIDDEN_ERROR), "Bluetooth is forbidden");
        map.put(Integer.valueOf(MISMATCH_PACKAGE_NAME_ERROR), "Data collector does not match the application's package name");
        map.put(Integer.valueOf(NONEXISTENT_DATA_COLLECTOR_ERROR), "Data collector not found");
        map.put(Integer.valueOf(SAMPLE_SET_TIMESTAMP_ERROR), "Sample set timestamp inconsistent with update time range");
        map.put(Integer.valueOf(ACTIVITY_RECORD_TIMESTAMPS_ERROR), "Invalid activity record timestamps");
        map.put(Integer.valueOf(USELESS_SAMPLE_POINT_ERROR), "Invalid sample point");
        map.put(Integer.valueOf(USELESS_TIMESTAMP_ERROR), "Invalid timestamp");
        map.put(Integer.valueOf(UNSUPPORTED_DATA_TYPE_ERROR), "The data type is unsupported");
        map.put(Integer.valueOf(NEED_APP_TRUSTLIST_ERROR), "Need application trust list");
        map.put(Integer.valueOf(DATA_IS_TOO_LARGE), "Data is too large,please check time range");
        map.put(Integer.valueOf(SYSTEM_VERSION_IS_INVALID), "Not support current system version");
        map.put(Integer.valueOf(AGGREGATION_DATA_TYPE_NOT_ALLOWED), "Statistical aggregation data type, it is not allowed to directly use the inserted data");
        map.put(Integer.valueOf(DATA_FIELD_MUST_FILLED), "The dataType of  insert data has required field must be filled");
        map.put(Integer.valueOf(UNUSED_DATA_TYPE_NOT_ALLOWED), "unused data type");
        map.put(Integer.valueOf(NO_NETWORK), "no internet access, please retry later");
        map.put(Integer.valueOf(INPUT_PARAM_MISSING), "api input param missing");
        map.put(Integer.valueOf(API_FUNCTION_UNAVAILABLE), "api function is unavailable.");
        map.put(Integer.valueOf(APP_HEALTH_NOT_INSTALLED), "health app not installed.");
        map.put(Integer.valueOf(APP_HEALTH_NOT_MATCH), "health app versionCode not match.");
        map.put(Integer.valueOf(LISTENER_ALREADY_EXIST), "RealTime listener already exist.");
        map.put(Integer.valueOf(LISTENER_NOT_EXIST), "RealTime listener not exist.");
        map.put(Integer.valueOf(HEALTH_APP_NOT_AUTHORISED), "Health app not authorise to health kit.");
        map.put(Integer.valueOf(READ_LATEST_NOT_SUPPORTED_ERROR), "The data type is not supported");
        map.put(Integer.valueOf(NO_REQUIRED_PERMISSION), "The function does not have the required permission.");
        map.put(Integer.valueOf(HUAWEIID_NOT_LOGGED_IN), "The Huawei account is not logged in.");
        map.put(Integer.valueOf(USER_OF_BETA_APP_EXCEED_RANGE), "The user of the beta application exceed the range.");
        map.put(Integer.valueOf(INVALID_CONTEXT), "Invalid context. Currently, the service context cannot be transferred to trigger forcible upgrade. Please use the activity context.");
        map.put(Integer.valueOf(HEALTH_RECORDS_NOT_EXIST), "Invalid healthRecordId. Enter an existing healthRecordId and try again.");
        map.put(Integer.valueOf(HEALTH_RECORDS_NOT_SUPPORT), "Invalid DataType. The current version supports tachycardia, bradycardia, health.record.sleep and their associated data types. please check.");
        map.put(Integer.valueOf(DICT_PARSE_ERROR), "An error occurs when the data dictionary is parsed. Please contact Huawei technical support.");
        map.put(Integer.valueOf(DEVICES_NOT_SUPPORT), "The device hardware may not support the step sensor. please try another device.");
        map.put(Integer.valueOf(INVALID_ACTIVITY_TYPE_IN_ACTIVITY_RECORD), "invalid activityType filled in, may not support ActivityRecordsController API, please check.");
        map.put(Integer.valueOf(JS_API_EXCEPTION_ERROR), "JS Api exception, please retry later.");
        map.put(Integer.valueOf(JS_API_PARAM_ERROR), "JS Api param error, please check the input params.");
        map.put(Integer.valueOf(ACTIVITY_SUMMARY_DATATYPE_NOT_SUPPORT), "Activity summary not support this dataType");
        map.put(Integer.valueOf(INTERFACE_NOT_SUPPORT_IN_REGION), "This interface is not supported in this region.");
        map.put(Integer.valueOf(QUERY_TIME_EXCEED_LIMIT), "The query time in this api exceed the limit 30 days, please check it");
        map.put(Integer.valueOf(DEVICE_NOT_SUPPORT), "The interface you called do not support on the device");
        map.put(Integer.valueOf(DISABLE_DATA_OPERATION), "Disable data reading and writing while screen locked");
    }
}
