package defpackage;

import com.huawei.health.trusport_ee_jni.trusport_eeJNI;

/* JADX INFO: loaded from: classes5.dex */
public final class hsa {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final hsa f13951a;
    public static final hsa aa;
    public static final hsa ab;
    public static final hsa ac;
    public static final hsa ad;
    public static final hsa ae;
    public static final hsa af;
    public static final hsa ag;
    public static final hsa ah;
    public static final hsa ai;
    public static final hsa aj;
    public static final hsa ak;
    public static final hsa al;
    public static final hsa am;
    public static final hsa an;
    public static final hsa ao;
    public static final hsa ap;
    public static final hsa aq;
    public static final hsa ar;
    public static final hsa as;
    public static final hsa at;
    public static final hsa au;
    public static final hsa av;
    public static final hsa aw;
    public static final hsa ax;
    public static final hsa ay;
    public static final hsa az;
    public static final hsa b;
    public static final hsa ba;
    public static final hsa bb;
    public static final hsa bc;
    public static final hsa bd;
    public static final hsa be;
    public static final hsa bf;
    public static final hsa bg;
    public static final hsa bh;
    public static final hsa bi;
    public static final hsa bj;
    public static final hsa bk;
    public static final hsa bl;
    public static final hsa bm;
    public static final hsa bn;
    public static final hsa bo;
    public static final hsa bp;
    public static final hsa bq;
    public static final hsa br;
    public static final hsa bs;
    public static final hsa bt;
    public static final hsa bu;
    public static final hsa bv;
    public static final hsa bw;
    public static final hsa bx;
    public static final hsa by;
    public static final hsa bz;
    public static final hsa c;
    public static final hsa ca;
    public static final hsa cb;
    public static final hsa cc;
    public static final hsa cd;
    public static final hsa ce;
    public static final hsa cf;
    public static final hsa cg;
    public static final hsa ch;
    public static final hsa ci;
    public static final hsa cj;
    public static final hsa ck;
    public static final hsa cl;
    public static final hsa cm;
    public static final hsa cn;
    public static final hsa co;
    public static final hsa cp;
    public static final hsa cq;
    public static final hsa cr;
    public static final hsa cs;
    public static final hsa ct;
    public static final hsa cu;
    public static final hsa cv;
    public static final hsa cw;
    public static final hsa cx;
    public static final hsa cy;
    public static final hsa cz;
    public static final hsa d;
    public static final hsa da;
    public static final hsa db;
    public static final hsa dc;
    public static final hsa dd;
    public static final hsa de;
    public static final hsa df;
    private static int di;
    public static final hsa dj;
    private static hsa[] dk;
    public static final hsa e;
    public static final hsa f;
    public static final hsa g;
    public static final hsa h;
    public static final hsa i;
    public static final hsa j;
    public static final hsa k;
    public static final hsa l;
    public static final hsa m;
    public static final hsa n;
    public static final hsa o;
    public static final hsa p;
    public static final hsa q;
    public static final hsa r;
    public static final hsa s;
    public static final hsa t;
    public static final hsa u;
    public static final hsa v;
    public static final hsa w;
    public static final hsa x;
    public static final hsa y;
    public static final hsa z;
    private final String dg;
    private final int dh;

    static {
        hsa hsaVar = new hsa("TS_ACTIVITY_OUTDOOR_RUN", trusport_eeJNI.TS_ACTIVITY_OUTDOOR_RUN_get());
        bn = hsaVar;
        hsa hsaVar2 = new hsa("TS_ACTIVITY_INDOOR_RUN");
        az = hsaVar2;
        hsa hsaVar3 = new hsa("TS_ACTIVITY_OUTDOOR_WALK");
        bq = hsaVar3;
        hsa hsaVar4 = new hsa("TS_ACTIVITY_INDOOR_WALK");
        bc = hsaVar4;
        hsa hsaVar5 = new hsa("TS_ACTIVITY_OUTDOOR_CYCLE");
        bo = hsaVar5;
        hsa hsaVar6 = new hsa("TS_ACTIVITY_INDOOR_CYCLE");
        av = hsaVar6;
        hsa hsaVar7 = new hsa("TS_ACTIVITY_ELLIPTICAL");
        ad = hsaVar7;
        hsa hsaVar8 = new hsa("TS_ACTIVITY_ROWER");
        bx = hsaVar8;
        hsa hsaVar9 = new hsa("TS_ACTIVITY_POOL_SWIM");
        ca = hsaVar9;
        hsa hsaVar10 = new hsa("TS_ACTIVITY_OPEN_WATER_SWIM");
        bi = hsaVar10;
        hsa hsaVar11 = new hsa("TS_ACTIVITY_MOUNTAIN_HIKE");
        bm = hsaVar11;
        hsa hsaVar12 = new hsa("TS_ACTIVITY_HIKE");
        ap = hsaVar12;
        hsa hsaVar13 = new hsa("TS_ACTIVITY_TRAIL_RUN");
        da = hsaVar13;
        hsa hsaVar14 = new hsa("TS_ACTIVITY_TRIATHLON");
        db = hsaVar14;
        hsa hsaVar15 = new hsa("TS_ACTIVITY_OTHER");
        bl = hsaVar15;
        hsa hsaVar16 = new hsa("TS_ACTIVITY_SKIING");
        ci = hsaVar16;
        hsa hsaVar17 = new hsa("TS_ACTIVITY_SNOWBOARDING");
        ck = hsaVar17;
        hsa hsaVar18 = new hsa("TS_ACTIVITY_CROSS_COUNTRY_SKIING");
        u = hsaVar18;
        hsa hsaVar19 = new hsa("TS_ACTIVITY_DRIVING_RANGE");
        z = hsaVar19;
        hsa hsaVar20 = new hsa("TS_ACTIVITY_GOLF_COURSE");
        am = hsaVar20;
        hsa hsaVar21 = new hsa("TS_ACTIVITY_JUMP_ROPE");
        ay = hsaVar21;
        hsa hsaVar22 = new hsa("TS_ACTIVITY_FREEDIVING");
        af = hsaVar22;
        hsa hsaVar23 = new hsa("TS_ACTIVITY_BREATHHOLD");
        s = hsaVar23;
        hsa hsaVar24 = new hsa("TS_ACTIVITY_STRENGTH");
        cs = hsaVar24;
        hsa hsaVar25 = new hsa("TS_ACTIVITY_SPINNING");
        cn = hsaVar25;
        hsa hsaVar26 = new hsa("TS_ACTIVITY_STEPPER");
        cq = hsaVar26;
        hsa hsaVar27 = new hsa("TS_ACTIVITY_AIR_WALKER");
        f13951a = hsaVar27;
        hsa hsaVar28 = new hsa("TS_ACTIVITY_HIIT");
        aq = hsaVar28;
        hsa hsaVar29 = new hsa("TS_ACTIVITY_AEROBICS");
        d = hsaVar29;
        hsa hsaVar30 = new hsa("TS_ACTIVITY_GROUP_TRAINING");
        aj = hsaVar30;
        hsa hsaVar31 = new hsa("TS_ACTIVITY_YOGA");
        dj = hsaVar31;
        hsa hsaVar32 = new hsa("TS_ACTIVITY_PILATES");
        bu = hsaVar32;
        hsa hsaVar33 = new hsa("TS_ACTIVITY_CROSS_FIT");
        v = hsaVar33;
        hsa hsaVar34 = new hsa("TS_ACTIVITY_FUNCTIONAL_TRAINING");
        al = hsaVar34;
        hsa hsaVar35 = new hsa("TS_ACTIVITY_PHYSICAL_TRAINING");
        bt = hsaVar35;
        hsa hsaVar36 = new hsa("TS_ACTIVITY_TAEKWONDO");
        cz = hsaVar36;
        hsa hsaVar37 = new hsa("TS_ACTIVITY_BOXING");
        q = hsaVar37;
        hsa hsaVar38 = new hsa("TS_ACTIVITY_FREE_SPARRING");
        ah = hsaVar38;
        hsa hsaVar39 = new hsa("TS_ACTIVITY_KARATE");
        bb = hsaVar39;
        hsa hsaVar40 = new hsa("TS_ACTIVITY_FENCING");
        ag = hsaVar40;
        hsa hsaVar41 = new hsa("TS_ACTIVITY_CORE_TRAINING");
        r = hsaVar41;
        hsa hsaVar42 = new hsa("TS_ACTIVITY_BODY_COMBAT");
        n = hsaVar42;
        hsa hsaVar43 = new hsa("TS_ACTIVITY_KENDO");
        bf = hsaVar43;
        hsa hsaVar44 = new hsa("TS_ACTIVITY_SINGLE_BAR");
        ce = hsaVar44;
        hsa hsaVar45 = new hsa("TS_ACTIVITY_PARALLEL_BARS");
        bp = hsaVar45;
        hsa hsaVar46 = new hsa("TS_ACTIVITY_BELLY_DANCE");
        i = hsaVar46;
        hsa hsaVar47 = new hsa("TS_ACTIVITY_JAZZ_DANCE");
        ba = hsaVar47;
        hsa hsaVar48 = new hsa("TS_ACTIVITY_LATIN_DANCE");
        bg = hsaVar48;
        hsa hsaVar49 = new hsa("TS_ACTIVITY_BALLET");
        g = hsaVar49;
        hsa hsaVar50 = new hsa("TS_ACTIVITY_STREET_DANCE");
        cp = hsaVar50;
        hsa hsaVar51 = new hsa("TS_ACTIVITY_PLAZA_DANCING");
        bw = hsaVar51;
        hsa hsaVar52 = new hsa("TS_ACTIVITY_DANCE");
        w = hsaVar52;
        hsa hsaVar53 = new hsa("TS_ACTIVITY_ROLLER_SKATING");
        by = hsaVar53;
        hsa hsaVar54 = new hsa("TS_ACTIVITY_MARTIAL_ARTS");
        be = hsaVar54;
        hsa hsaVar55 = new hsa("TS_ACTIVITY_TAI_CHI");
        cx = hsaVar55;
        hsa hsaVar56 = new hsa("TS_ACTIVITY_HULA_HOOP");
        au = hsaVar56;
        hsa hsaVar57 = new hsa("TS_ACTIVITY_FRISBEE");
        ak = hsaVar57;
        hsa hsaVar58 = new hsa("TS_ACTIVITY_DARTS");
        aa = hsaVar58;
        hsa hsaVar59 = new hsa("TS_ACTIVITY_ARCHERY");
        e = hsaVar59;
        hsa hsaVar60 = new hsa("TS_ACTIVITY_HORSE_RIDING");
        ar = hsaVar60;
        hsa hsaVar61 = new hsa("TS_ACTIVITY_LASER_TAG");
        bh = hsaVar61;
        hsa hsaVar62 = new hsa("TS_ACTIVITY_KITE_FLYING");
        bd = hsaVar62;
        hsa hsaVar63 = new hsa("TS_ACTIVITY_TUG_OF_WAR");
        dd = hsaVar63;
        hsa hsaVar64 = new hsa("TS_ACTIVITY_SWINGING");
        ct = hsaVar64;
        hsa hsaVar65 = new hsa("TS_ACTIVITY_STAIR_CLIMBING");
        co = hsaVar65;
        hsa hsaVar66 = new hsa("TS_ACTIVITY_OBSTACLE_RACE");
        bk = hsaVar66;
        hsa hsaVar67 = new hsa("TS_ACTIVITY_FISHING");
        ai = hsaVar67;
        hsa hsaVar68 = new hsa("TS_ACTIVITY_BADMINTON");
        b = hsaVar68;
        hsa hsaVar69 = new hsa("TS_ACTIVITY_TABLE_TENNIS");
        cw = hsaVar69;
        hsa hsaVar70 = new hsa("TS_ACTIVITY_TENNIS");
        cy = hsaVar70;
        hsa hsaVar71 = new hsa("TS_ACTIVITY_POOL");
        bv = hsaVar71;
        hsa hsaVar72 = new hsa("TS_ACTIVITY_BOWLING");
        l = hsaVar72;
        hsa hsaVar73 = new hsa("TS_ACTIVITY_VOLLEYBALL");
        de = hsaVar73;
        hsa hsaVar74 = new hsa("TS_ACTIVITY_SHUTTLECOCK");
        cd = hsaVar74;
        hsa hsaVar75 = new hsa("TS_ACTIVITY_HANDBALL");
        as = hsaVar75;
        hsa hsaVar76 = new hsa("TS_ACTIVITY_BASEBALL");
        j = hsaVar76;
        hsa hsaVar77 = new hsa("TS_ACTIVITY_SOFTBALL");
        ch = hsaVar77;
        hsa hsaVar78 = new hsa("TS_ACTIVITY_CRICKET");
        x = hsaVar78;
        hsa hsaVar79 = new hsa("TS_ACTIVITY_FOOTBALL");
        ae = hsaVar79;
        hsa hsaVar80 = new hsa("TS_ACTIVITY_BEACH_SOCCER");
        h = hsaVar80;
        hsa hsaVar81 = new hsa("TS_ACTIVITY_BEACH_VOLLEYBALL");
        f = hsaVar81;
        hsa hsaVar82 = new hsa("TS_ACTIVITY_GATEBALL");
        an = hsaVar82;
        hsa hsaVar83 = new hsa("TS_ACTIVITY_HOCKEY");
        ao = hsaVar83;
        hsa hsaVar84 = new hsa("TS_ACTIVITY_SQUASH");
        cm = hsaVar84;
        hsa hsaVar85 = new hsa("TS_ACTIVITY_SEPAK_TAKRAW");
        cg = hsaVar85;
        hsa hsaVar86 = new hsa("TS_ACTIVITY_DODGEBALL");
        ac = hsaVar86;
        hsa hsaVar87 = new hsa("TS_ACTIVITY_SAILING");
        cf = hsaVar87;
        hsa hsaVar88 = new hsa("TS_ACTIVITY_SURFING");
        cv = hsaVar88;
        hsa hsaVar89 = new hsa("TS_ACTIVITY_RAFTING");
        bz = hsaVar89;
        hsa hsaVar90 = new hsa("TS_ACTIVITY_DRAGON_BOATING");
        ab = hsaVar90;
        hsa hsaVar91 = new hsa("TS_ACTIVITY_CANOEING");
        t = hsaVar91;
        hsa hsaVar92 = new hsa("TS_ACTIVITY_ROWING");
        cc = hsaVar92;
        hsa hsaVar93 = new hsa("TS_ACTIVITY_WATER_SCOOTER");
        df = hsaVar93;
        hsa hsaVar94 = new hsa("TS_ACTIVITY_SUP");
        cu = hsaVar94;
        hsa hsaVar95 = new hsa("TS_ACTIVITY_ICE_SKATING");
        ax = hsaVar95;
        hsa hsaVar96 = new hsa("TS_ACTIVITY_ICE_HOCKEY");
        aw = hsaVar96;
        hsa hsaVar97 = new hsa("TS_ACTIVITY_CURLING");
        y = hsaVar97;
        hsa hsaVar98 = new hsa("TS_ACTIVITY_BOBSLEIGH");
        o = hsaVar98;
        hsa hsaVar99 = new hsa("TS_ACTIVITY_SLEDDING");
        cj = hsaVar99;
        hsa hsaVar100 = new hsa("TS_ACTIVITY_BIATHLON");
        m = hsaVar100;
        hsa hsaVar101 = new hsa("TS_ACTIVITY_SKATEBOARDING");
        cl = hsaVar101;
        hsa hsaVar102 = new hsa("TS_ACTIVITY_ROCK_CLIMBING");
        cb = hsaVar102;
        hsa hsaVar103 = new hsa("TS_ACTIVITY_BUNGEE_JUMPING");
        p = hsaVar103;
        hsa hsaVar104 = new hsa("TS_ACTIVITY_PARKOUR");
        bs = hsaVar104;
        hsa hsaVar105 = new hsa("TS_ACTIVITY_BMX");
        k = hsaVar105;
        hsa hsaVar106 = new hsa("TS_ACTIVITY_ORIENTEERING");
        bj = hsaVar106;
        hsa hsaVar107 = new hsa("TS_ACTIVITY_PARACHUTING");
        br = hsaVar107;
        hsa hsaVar108 = new hsa("TS_ACTIVITY_AUTO_RACING");
        c = hsaVar108;
        hsa hsaVar109 = new hsa("TS_ACTIVITY_SWIMMING");
        cr = hsaVar109;
        hsa hsaVar110 = new hsa("TS_ACTIVITY_IDLE");
        at = hsaVar110;
        hsa hsaVar111 = new hsa("TS_ACTIVITY_UNKNOWN");
        dc = hsaVar111;
        dk = new hsa[]{hsaVar, hsaVar2, hsaVar3, hsaVar4, hsaVar5, hsaVar6, hsaVar7, hsaVar8, hsaVar9, hsaVar10, hsaVar11, hsaVar12, hsaVar13, hsaVar14, hsaVar15, hsaVar16, hsaVar17, hsaVar18, hsaVar19, hsaVar20, hsaVar21, hsaVar22, hsaVar23, hsaVar24, hsaVar25, hsaVar26, hsaVar27, hsaVar28, hsaVar29, hsaVar30, hsaVar31, hsaVar32, hsaVar33, hsaVar34, hsaVar35, hsaVar36, hsaVar37, hsaVar38, hsaVar39, hsaVar40, hsaVar41, hsaVar42, hsaVar43, hsaVar44, hsaVar45, hsaVar46, hsaVar47, hsaVar48, hsaVar49, hsaVar50, hsaVar51, hsaVar52, hsaVar53, hsaVar54, hsaVar55, hsaVar56, hsaVar57, hsaVar58, hsaVar59, hsaVar60, hsaVar61, hsaVar62, hsaVar63, hsaVar64, hsaVar65, hsaVar66, hsaVar67, hsaVar68, hsaVar69, hsaVar70, hsaVar71, hsaVar72, hsaVar73, hsaVar74, hsaVar75, hsaVar76, hsaVar77, hsaVar78, hsaVar79, hsaVar80, hsaVar81, hsaVar82, hsaVar83, hsaVar84, hsaVar85, hsaVar86, hsaVar87, hsaVar88, hsaVar89, hsaVar90, hsaVar91, hsaVar92, hsaVar93, hsaVar94, hsaVar95, hsaVar96, hsaVar97, hsaVar98, hsaVar99, hsaVar100, hsaVar101, hsaVar102, hsaVar103, hsaVar104, hsaVar105, hsaVar106, hsaVar107, hsaVar108, hsaVar109, hsaVar110, hsaVar111};
        di = 0;
    }

    public final int e() {
        return this.dh;
    }

    public String toString() {
        return this.dg;
    }

    private hsa(String str) {
        this.dg = str;
        int i2 = di;
        di = i2 + 1;
        this.dh = i2;
    }

    private hsa(String str, int i2) {
        this.dg = str;
        this.dh = i2;
        di = i2 + 1;
    }
}
