package com.huawei.health.sportservice.constants;

/* JADX INFO: loaded from: classes4.dex */
public enum SportParamsType {
    SPORT_LAUNCH_PARAS,
    AI_ROPE_PARAS,
    AI_ROPE_INPUT_IMAGE,
    AI_ROPE_SOURCE_LISTENER,
    DEVICE_CALLBACK_AW70,
    AI_SPORT_EXAM_SOURCE_LISTENER,
    AI_TRAIN_SOURCE_LISTENER,
    PRE_STATUS_SOURCE_LISTENER,
    AI_TRAIN_TEMPLATE_DATA,
    PARAMS_PRODUCER_MAP,
    COURSE_INFO,
    HEART_RATE_CONTROL_LOCK,
    SPORT_BEAT_CHANGE,
    DEVICES_DATA_CHANGE_FIRST
}
