package com.huawei.health.marketing.datatype;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.autonavi.amap.mapcore.tools.GlMapUtil;
import com.google.android.gms.wearable.WearableStatusCodes;
import com.huawei.android.airsharing.api.IEventListener;
import com.huawei.hihealthservice.old.model.OldToNewMotionPath;
import com.huawei.hms.mlsdk.asr.engine.AsrError;
import com.huawei.operation.utils.Constants;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes4.dex */
public class PositionIdSet extends ArrayList<Integer> {
    private static final ArrayList<Integer> BLOOD_OXYGEN_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> BLOOD_OXYGEN_POSITION_ID_LIST;
    private static final ArrayList<Integer> BLOOD_PRESSURE_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> BLOOD_PRESSURE_POSITION_ID_LIST;
    private static final ArrayList<Integer> BLOOD_SUGAR_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> BLOOD_SUGAR_POSITION_ID_LIST;
    private static final ArrayList<Integer> CYCLE_CALENDAR_POSITION_ID_LIST;
    private static final ArrayList<Integer> DEVICE_DETAIL_POSITION_ID_LIST;
    private static final ArrayList<Integer> DEVICE_POSITION_ID_LIST;
    private static final ArrayList<Integer> DISCOVERY_POSITION_ID_LIST;
    private static final ArrayList<Integer> FAMILY_ROOM_POSITION_ID_LIST;
    private static final ArrayList<Integer> FITNESS_POSITION_ID_LIST;
    private static final ArrayList<Integer> FITNESS_RESULT_POSITION_ID_LIST;
    private static final ArrayList<Integer> HEALTH_LIFE_POSITION_ID_LIST;
    private static final ArrayList<Integer> HEALTH_POSITION_ID_LIST;
    private static final ArrayList<Integer> HEART_RATE_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> HEART_RATE_POSITION_ID_LIST;
    private static final ArrayList<Integer> HIKING_POSITION_ID_LIST;
    private static final ArrayList<Integer> INDOOR_RUNNING_POSITION_ID_LIST;
    private static final ArrayList<Integer> INTENSITY_POSITION_ID_LIST;
    private static final ArrayList<Integer> KAKA_POSITION_ID_LIST;
    private static final ArrayList<Integer> MOUNTAINERRING_POSITION_ID_LIST;
    private static final ArrayList<Integer> MY_PLAN_POSITION_ID_LIST;
    private static final ArrayList<Integer> MY_POSITION_ID_LIST;
    private static final Map<Integer, ArrayList<Integer>> POSITION_ID_MAP;
    private static final ArrayList<Integer> PRESSURE_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> PRESSURE_POSITION_ID_LIST;
    private static final ArrayList<Integer> RECOMMENDED_POSITION_ID_LIST;
    private static final ArrayList<Integer> RIDING_POSITION_ID_LIST;
    private static final ArrayList<Integer> ROPE_POSITION_ID_LIST;
    private static final ArrayList<Integer> ROPE_SKIP_INTRODUCTION_POSITION_ID_LIST;
    private static final ArrayList<Integer> RUNNING_POSITION_ID_LIST;
    private static final ArrayList<Integer> RUNNING_RESULT_POSITION_ID_LIST;
    private static final ArrayList<Integer> SLEEP_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> SLEEP_POSITION_ID_LIST;
    private static final ArrayList<Integer> SPORT_POSITION_ID_LIST;
    private static final ArrayList<Integer> SPORT_RECORD_POSITION_ID_LIST;
    private static final ArrayList<Integer> STEP_POSITION_ID_LIST;
    private static final ArrayList<Integer> TEMPERATURE_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> TEMPERATURE_POSITION_ID_LIST;
    private static final ArrayList<Integer> TRAIN_DETAIL_POSITION_ID_LIST;
    private static final ArrayList<Integer> VO2MAX_POSITION_ID_LIST;
    private static final ArrayList<Integer> WALK_POSITION_ID_LIST;
    private static final ArrayList<Integer> WALK_RESULT_POSITION_ID_LIST;
    private static final ArrayList<Integer> WEIGHT_NO_DATA_POSITION_ID_LIST;
    private static final ArrayList<Integer> WEIGHT_POSITION_ID_LIST;
    private static final ArrayList<Integer> YOGA_POSITION_ID_LIST;

    static {
        HashMap map = new HashMap();
        POSITION_ID_MAP = map;
        ArrayList<Integer> arrayList = new ArrayList<>();
        HEALTH_POSITION_ID_LIST = arrayList;
        arrayList.add(2001);
        arrayList.add(3001);
        arrayList.add(2046);
        arrayList.add(8002);
        ArrayList<Integer> arrayList2 = new ArrayList<>();
        DISCOVERY_POSITION_ID_LIST = arrayList2;
        arrayList2.add(2002);
        arrayList2.add(3002);
        arrayList2.add(4001);
        arrayList2.add(2046);
        arrayList2.add(8002);
        ArrayList<Integer> arrayList3 = new ArrayList<>();
        DEVICE_POSITION_ID_LIST = arrayList3;
        arrayList3.add(2003);
        arrayList3.add(3003);
        arrayList3.add(2046);
        arrayList3.add(8002);
        ArrayList<Integer> arrayList4 = new ArrayList<>();
        MY_POSITION_ID_LIST = arrayList4;
        arrayList4.add(2004);
        arrayList4.add(3004);
        arrayList4.add(2046);
        arrayList4.add(8002);
        ArrayList<Integer> arrayList5 = new ArrayList<>();
        SPORT_POSITION_ID_LIST = arrayList5;
        arrayList5.add(2046);
        arrayList5.add(2050);
        arrayList5.add(3044);
        arrayList5.add(8002);
        ArrayList<Integer> arrayList6 = new ArrayList<>();
        SPORT_RECORD_POSITION_ID_LIST = arrayList6;
        arrayList6.add(2005);
        arrayList6.add(Integer.valueOf(IEventListener.EVENT_ID_DEVICE_DISCONN_SUCC));
        arrayList6.add(4152);
        arrayList6.add(4153);
        arrayList6.add(4154);
        arrayList6.add(4155);
        arrayList6.add(4174);
        arrayList6.add(4175);
        arrayList6.add(4176);
        arrayList6.add(4162);
        ArrayList<Integer> arrayList7 = new ArrayList<>();
        HEALTH_LIFE_POSITION_ID_LIST = arrayList7;
        arrayList7.add(2006);
        arrayList7.add(Integer.valueOf(IEventListener.EVENT_ID_DEVICE_SCAN_FINISH));
        arrayList7.add(4003);
        ArrayList<Integer> arrayList8 = new ArrayList<>();
        CYCLE_CALENDAR_POSITION_ID_LIST = arrayList8;
        arrayList8.add(2007);
        arrayList8.add(Integer.valueOf(IEventListener.EVENT_ID_DEVICE_RTSP_CONN));
        arrayList8.add(4004);
        ArrayList<Integer> arrayList9 = new ArrayList<>();
        HEART_RATE_POSITION_ID_LIST = arrayList9;
        arrayList9.add(2008);
        arrayList9.add(Integer.valueOf(IEventListener.EVENT_ID_DEVICE_UPDATE));
        arrayList9.add(4005);
        ArrayList<Integer> arrayList10 = new ArrayList<>();
        BLOOD_OXYGEN_POSITION_ID_LIST = arrayList10;
        arrayList10.add(2009);
        arrayList10.add(3009);
        arrayList10.add(4006);
        ArrayList<Integer> arrayList11 = new ArrayList<>();
        PRESSURE_POSITION_ID_LIST = arrayList11;
        arrayList11.add(2010);
        arrayList11.add(3010);
        arrayList11.add(4007);
        ArrayList<Integer> arrayList12 = new ArrayList<>();
        SLEEP_POSITION_ID_LIST = arrayList12;
        arrayList12.add(2011);
        arrayList12.add(Integer.valueOf(IEventListener.EVENT_ID_DEVICE_DLNA_CONN_SUCC));
        arrayList12.add(Integer.valueOf(WearableStatusCodes.WIFI_CREDENTIAL_SYNC_NO_CREDENTIAL_FETCHED));
        ArrayList<Integer> arrayList13 = new ArrayList<>();
        WEIGHT_POSITION_ID_LIST = arrayList13;
        arrayList13.add(2012);
        arrayList13.add(Integer.valueOf(IEventListener.EVENT_ID_DEVICE_REQUEST_CONN));
        arrayList13.add(4009);
        ArrayList<Integer> arrayList14 = new ArrayList<>();
        BLOOD_SUGAR_POSITION_ID_LIST = arrayList14;
        arrayList14.add(2013);
        arrayList14.add(Integer.valueOf(IEventListener.EVENT_ID_DEVICE_REQUEST_PLAY));
        arrayList14.add(4010);
        ArrayList<Integer> arrayList15 = new ArrayList<>();
        BLOOD_PRESSURE_POSITION_ID_LIST = arrayList15;
        arrayList15.add(2014);
        arrayList15.add(Integer.valueOf(IEventListener.EVENT_ID_GRAB_STATE_CHANGED));
        arrayList15.add(4011);
        ArrayList<Integer> arrayList16 = new ArrayList<>();
        FAMILY_ROOM_POSITION_ID_LIST = arrayList16;
        arrayList16.add(2015);
        arrayList16.add(3015);
        ArrayList<Integer> arrayList17 = new ArrayList<>();
        RUNNING_POSITION_ID_LIST = arrayList17;
        arrayList17.add(2016);
        arrayList17.add(3016);
        ArrayList<Integer> arrayList18 = new ArrayList<>();
        INDOOR_RUNNING_POSITION_ID_LIST = arrayList18;
        arrayList18.add(2017);
        arrayList18.add(3017);
        ArrayList<Integer> arrayList19 = new ArrayList<>();
        FITNESS_POSITION_ID_LIST = arrayList19;
        arrayList19.add(2018);
        arrayList19.add(3018);
        ArrayList<Integer> arrayList20 = new ArrayList<>();
        WALK_POSITION_ID_LIST = arrayList20;
        arrayList20.add(2019);
        arrayList20.add(3019);
        ArrayList<Integer> arrayList21 = new ArrayList<>();
        RIDING_POSITION_ID_LIST = arrayList21;
        arrayList21.add(3020);
        arrayList21.add(2020);
        ArrayList<Integer> arrayList22 = new ArrayList<>();
        STEP_POSITION_ID_LIST = arrayList22;
        arrayList22.add(2026);
        arrayList22.add(3021);
        arrayList22.add(4017);
        ArrayList<Integer> arrayList23 = new ArrayList<>();
        INTENSITY_POSITION_ID_LIST = arrayList23;
        arrayList23.add(2027);
        arrayList23.add(Integer.valueOf(AsrError.SERVICE_OUT_CREDIT));
        arrayList23.add(4018);
        ArrayList<Integer> arrayList24 = new ArrayList<>();
        RUNNING_RESULT_POSITION_ID_LIST = arrayList24;
        arrayList24.add(2021);
        ArrayList<Integer> arrayList25 = new ArrayList<>();
        WALK_RESULT_POSITION_ID_LIST = arrayList25;
        arrayList25.add(2024);
        ArrayList<Integer> arrayList26 = new ArrayList<>();
        FITNESS_RESULT_POSITION_ID_LIST = arrayList26;
        arrayList26.add(2022);
        arrayList26.add(2023);
        arrayList26.add(4158);
        ArrayList<Integer> arrayList27 = new ArrayList<>();
        KAKA_POSITION_ID_LIST = arrayList27;
        arrayList27.add(2037);
        arrayList27.add(3032);
        ArrayList<Integer> arrayList28 = new ArrayList<>();
        ROPE_POSITION_ID_LIST = arrayList28;
        arrayList28.add(2028);
        arrayList28.add(3023);
        ArrayList<Integer> arrayList29 = new ArrayList<>();
        YOGA_POSITION_ID_LIST = arrayList29;
        arrayList29.add(2029);
        arrayList29.add(3024);
        ArrayList<Integer> arrayList30 = new ArrayList<>();
        HIKING_POSITION_ID_LIST = arrayList30;
        arrayList30.add(Integer.valueOf(Constants.START_TO_MAIN_ACTIVITY));
        arrayList30.add(3027);
        ArrayList<Integer> arrayList31 = new ArrayList<>();
        MOUNTAINERRING_POSITION_ID_LIST = arrayList31;
        arrayList31.add(2031);
        arrayList31.add(3026);
        ArrayList<Integer> arrayList32 = new ArrayList<>();
        TEMPERATURE_POSITION_ID_LIST = arrayList32;
        arrayList32.add(2036);
        arrayList32.add(3031);
        arrayList32.add(4027);
        ArrayList<Integer> arrayList33 = new ArrayList<>();
        HEART_RATE_NO_DATA_POSITION_ID_LIST = arrayList33;
        arrayList33.add(2038);
        arrayList33.add(3033);
        arrayList33.add(4028);
        ArrayList<Integer> arrayList34 = new ArrayList<>();
        BLOOD_OXYGEN_NO_DATA_POSITION_ID_LIST = arrayList34;
        arrayList34.add(2039);
        arrayList34.add(3034);
        arrayList34.add(4029);
        ArrayList<Integer> arrayList35 = new ArrayList<>();
        PRESSURE_NO_DATA_POSITION_ID_LIST = arrayList35;
        arrayList35.add(Integer.valueOf(Constants.START_TO_INDOOR_RUNNING));
        arrayList35.add(3035);
        arrayList35.add(4030);
        ArrayList<Integer> arrayList36 = new ArrayList<>();
        SLEEP_NO_DATA_POSITION_ID_LIST = arrayList36;
        arrayList36.add(2041);
        arrayList36.add(3036);
        arrayList36.add(4031);
        ArrayList<Integer> arrayList37 = new ArrayList<>();
        WEIGHT_NO_DATA_POSITION_ID_LIST = arrayList37;
        arrayList37.add(2042);
        arrayList37.add(3037);
        arrayList37.add(4032);
        ArrayList<Integer> arrayList38 = new ArrayList<>();
        BLOOD_SUGAR_NO_DATA_POSITION_ID_LIST = arrayList38;
        arrayList38.add(2043);
        arrayList38.add(3038);
        arrayList38.add(4033);
        ArrayList<Integer> arrayList39 = new ArrayList<>();
        BLOOD_PRESSURE_NO_DATA_POSITION_ID_LIST = arrayList39;
        arrayList39.add(2044);
        arrayList39.add(3039);
        arrayList39.add(4034);
        ArrayList<Integer> arrayList40 = new ArrayList<>();
        TEMPERATURE_NO_DATA_POSITION_ID_LIST = arrayList40;
        arrayList40.add(2045);
        arrayList40.add(3040);
        arrayList40.add(4035);
        ArrayList<Integer> arrayList41 = new ArrayList<>();
        ROPE_SKIP_INTRODUCTION_POSITION_ID_LIST = arrayList41;
        arrayList41.add(4037);
        ArrayList<Integer> arrayList42 = new ArrayList<>();
        VO2MAX_POSITION_ID_LIST = arrayList42;
        arrayList42.add(3041);
        arrayList42.add(2047);
        arrayList42.add(4039);
        ArrayList<Integer> arrayList43 = new ArrayList<>();
        RECOMMENDED_POSITION_ID_LIST = arrayList43;
        arrayList43.add(3042);
        arrayList43.add(2048);
        ArrayList<Integer> arrayList44 = new ArrayList<>();
        DEVICE_DETAIL_POSITION_ID_LIST = arrayList44;
        arrayList44.add(4087);
        ArrayList<Integer> arrayList45 = new ArrayList<>();
        MY_PLAN_POSITION_ID_LIST = arrayList45;
        arrayList45.add(4159);
        ArrayList<Integer> arrayList46 = new ArrayList<>();
        TRAIN_DETAIL_POSITION_ID_LIST = arrayList46;
        arrayList46.add(4160);
        map.put(18, arrayList);
        map.put(401, arrayList5);
        map.put(16, arrayList2);
        map.put(15, arrayList3);
        map.put(110, arrayList4);
        map.put(120, arrayList6);
        map.put(19, arrayList7);
        map.put(21, arrayList8);
        map.put(9, arrayList9);
        map.put(20, arrayList10);
        map.put(3, arrayList11);
        map.put(1, arrayList12);
        map.put(2, arrayList13);
        map.put(8, arrayList14);
        map.put(7, arrayList15);
        map.put(Integer.valueOf(OldToNewMotionPath.SPORT_TYPE_CROSS_COUNTRY_RACE), arrayList16);
        map.put(4, arrayList17);
        map.put(240, arrayList18);
        map.put(22, arrayList19);
        map.put(5, arrayList20);
        map.put(6, arrayList21);
        map.put(410, arrayList43);
        map.put(10, arrayList22);
        map.put(11, arrayList23);
        map.put(230, arrayList24);
        map.put(250, arrayList25);
        map.put(260, arrayList26);
        map.put(290, arrayList27);
        map.put(390, arrayList28);
        map.put(23, arrayList29);
        map.put(25, arrayList30);
        map.put(26, arrayList31);
        map.put(24, arrayList32);
        map.put(360, arrayList33);
        map.put(380, arrayList34);
        map.put(330, arrayList35);
        map.put(310, arrayList36);
        map.put(Integer.valueOf(GlMapUtil.DEVICE_DISPLAY_DPI_HIGH), arrayList37);
        map.put(350, arrayList38);
        map.put(340, arrayList39);
        map.put(370, arrayList40);
        map.put(400, arrayList41);
        map.put(17, arrayList42);
        map.put(421, arrayList44);
        map.put(Integer.valueOf(TypedValues.CycleType.TYPE_CUSTOM_WAVE_SHAPE), arrayList45);
        map.put(423, arrayList46);
    }

    public static ArrayList<Integer> getPositionIdList(int i) {
        ArrayList<Integer> arrayList = POSITION_ID_MAP.get(Integer.valueOf(i));
        return arrayList == null ? new ArrayList<>() : arrayList;
    }
}
