package com.huawei.hwdevice.mainprocess.mgr.hwmywatchfacemgr.constant;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes6.dex */
public class WatchFaceConstant {
    public static final int ALBUM_EXPAND_TYPE = 2;
    public static final String AOD_PICTURE_HASH_KEY = "aodPicture_{watchFaceId}_{watchFaceVersion}";
    public static final String APPLY_POWER_WATCHFACE_KIT_CHECK_REASON = "user-watchfaceRequest";
    public static final int BACKGROUND_TYPE_BIN = 2;
    public static final int BIN_FILE_TYPE_32 = 0;
    public static final String BIN_SUFFIX = ".bin";
    public static final int CALLBACK_LOG_SLICE = 5;
    public static final int CANCEL_FILE_TRANSFER_SUCCESS = 20003;
    public static final int COMMAND_SUCCESS = 100000;
    public static final String COVER_PICTURE_HASH_KEY = "coverPicture_{watchFaceId}_{watchFaceVersion}";
    public static final int CURRENT_WATCH_FACE_CHANGE = 1;
    public static final String DETAIL_HASH_KEY = "watchFaceDetail_{watchFaceId}_{watchFaceVersion}";
    public static final String DETAIL_REQUEST_URL = "operationgeneral/app/v1/watchfaces/{watchFaceId}";
    public static final String DEVICE_TYPE_INFO_REQUEST_URL = "operationgeneral/app/v1/watchfaces/devicetypes/{deviceType}";
    public static final int EMPTY_BACKGROUND_COUNT = 0;
    public static final int EMPTY_PROGRESS_PERCENT = 0;
    public static final String ENGLISH_COMMA = ",";
    public static final String ENGLISH_UNDERLINE = "_";
    public static final int FILE_TRANSFER_DISCONNECT = 10001;
    public static final int FILE_TRANSFER_NOT_EXIST = 10003;
    public static final int FILE_TRANSFER_ONE_BACKGROUND = 1;
    public static final int FILE_TRANSFER_OTHER_ERROR = -1;
    public static final int FILE_TRANSFER_OUT_OF_MEMORY = 10006;
    public static final int FILE_TRANSFER_TIME_OUT = 10002;
    public static final int FILE_TRANSFER_TWO_BACKGROUND = 2;
    public static final int FILE_TYPE_ALBUM_BACKGROUND = 1;
    public static final int FILE_TYPE_KALEIDOSCOPE = 14;
    public static final int FILE_TYPE_MATERIAL_IMAGE = 23;
    public static final int FILE_TYPE_PHOTO = 3;
    public static final int FILE_TYPE_VIDEO = 10;
    public static final int FILE_TYPE_WATCH_FACE_VIDEO = 19;
    public static final int FILE_TYPE_WEAR = 25;
    public static final int FILE_TYPE_WEAR_BACKGROUND = 17;
    public static final int FILE_TYPE_WEAR_PREVIEW = 16;
    public static final int GET_IMAGE_TIMEOUT = 5000;
    public static final String HWT_SAVE_PATH = "/net_cache/wface.hwt";
    public static final String HWT_SUFFIX = ".hwt";
    public static final String ICON_PICTURE_HASH_KEY = "iconPicture_{watchFaceId}_{watchFaceVersion}";
    public static final int ICON_PICTURE_STATUS_ERROR = 1;
    public static final int ICON_PICTURE_STATUS_NORMAL = 0;
    public static final int ICON_PICTURE_STATUS_TRANSPARENT = 2;
    public static final String INSTALL_CUSTOM_CONFIG_KEY = "customConfig";
    public static final int INT_BIT_FIFTH = 32;
    public static final int INT_BIT_FOURTH = 16;
    public static final int INT_BIT_SEVEN = 128;
    public static final int INT_BIT_SIXTH = 64;
    public static final int IS_CURRENT_WATCH_FACE_MASK = 1;
    public static final int IS_PRESET_WATCHFACE_MASK = 2;
    public static final int IS_SUPPORT_DELETE_MASK = 4;
    public static final int KALEIDOSCOPE_EXPAND_TYPE = 3;
    public static final int LANGUAGE_MODE_CN = 2;
    public static final int LANGUAGE_MODE_EN = 1;
    public static final int MAX_ALBUM_WATCH_FACE_LENGTH = 20;
    public static final int MAX_PERCENT = 100;
    public static final String MP4_SUFFIX = ".mp4";
    public static final int NOT_REPORT_SUPPORT_GAUSSIAN_COLOR = -1;
    public static final int NOT_REPORT_SUPPORT_ONE_TOUCH = -1;
    public static final int NO_DEVICE_FOUND = 30004;
    public static final int OPERATE_APPLY_WATCHFACE = 1;
    public static final int OPERATE_DELETE_WATCHFACE = 2;
    public static final int OPERATE_RESULT_NEED_RECEIVE = 1;
    public static final int OPERATE_UPDATE_WATCHFACE = 4;
    public static final String PACKAGE_REQUEST_URL = "operationgeneral/app/v1/watchfaces/{watchFaceId}/packages";
    public static final int PERCENT_MULTIPLIER = 100;
    public static final String PNG_SUFFIX = ".png";
    public static final String PRESET_RES = "A100";
    public static final int PREVIEW_IMG_URL_EXPIRATION_TIME = 600000;
    public static final String PREVIEW_RES = "preview";
    public static final int PROGRESS_STEP_THRESHOLD = 10;
    public static final String RECOMMEND_HASH_KEY = "RECOMMEND_KEY";
    public static final String RECOMMEND_REQUEST_URL = "operationgeneral/app/v1/watchfaces";
    public static final int REPORT_NOT_SUPPORT_ONE_TOUCH = 0;
    public static final int REPORT_SUPPORT_ONE_TOUCH = 1;
    public static final int REQUEST_CACHE_DURATION = 604800000;
    public static final String RESOURCES_ASSETS = "wear-sdk-resources";
    public static final int RESULT_CODE_FAILED = -1;
    public static final int RESULT_CODE_PROGRESS = 2;
    public static final int RESULT_CODE_SUCCESS = 0;
    public static final String ROOT_PATH_KALEIDOSCOPE = "/14/";
    public static final String ROOT_PATH_PHOTO = File.separator + "watchfacePhoto" + File.separator;
    public static final String ROOT_PATH_VIDEO = File.separator + "watchfaceVideo" + File.separator;
    public static final Map<String, String> SCREE_MAP = new HashMap() { // from class: com.huawei.hwdevice.mainprocess.mgr.hwmywatchfacemgr.constant.WatchFaceConstant.1
        {
            put("390*390", "HWHD01");
            put("454*454", "HWHD02");
            put("120*240", "HWHD03");
            put("80*160", "HWHD04");
            put("188*460", "HWHD05");
            put("280*456", "HWHD06");
            put("194*368", "HWHD07");
            put("320*320", "HWHD08");
            put("466*466", "HWHD09");
            put("320*360", "HWHD10");
            put("336*480", "HWHD11");
            put("240*240", "HWHD12");
            put("408*480", "HWHD13");
            put("286*482", "HWHD14");
        }
    };
    public static final int SERVER_MODE_CN_NETWORK = 1;
    public static final int STICKER_EXPAND_TYPE = 5;
    public static final String STRING_INDEX_DOT = ".";
    public static final int SUPPORT_NOT_TINT_COLOR = 0;
    public static final String SYMBOL_SPLIT_POINT = ".";
    public static final String TEMPLATES_CIRCLE_NAME = "templates.xml";
    public static final String TEMPLATES_CUSTOM_NAME = "templates_custom.xml";
    public static final int TRANSFER_WATCH_FACE_SUCCESS = 2;
    public static final int TYPE_COLOR_PHOTO = 1;
    public static final int TYPE_COLOR_TIME = 2;
    public static final int VIDEO_EXPAND_TYPE = 1;
    public static final String WALLPAPER_RES = "wallpaper";
    public static final String WATCH_FACE_BIN_PATH = "/watchFace/pack/watchface.bin";
    public static final int WATCH_FACE_CLIP_CONFIG = 3;
    public static final int WATCH_FACE_CLIP_PHOTO = 2;
    public static final int WATCH_FACE_DEFAULT_HEIGHT = 466;
    public static final int WATCH_FACE_DEFAULT_WIDTH = 466;
    public static final String WATCH_FACE_PACK_DE_PATH = "/watchFace/pack";
    public static final String WATCH_FACE_PACK_PATH = "/watchFace/com.huawei.watchface";
    public static final String WATCH_FACE_PATH = "/watchFace";
    public static final int WATCH_FACE_PHOTO_BACKGROUND = 1;
    public static final int WATCH_FACE_SIGN_FAILED_ERROR_100007 = 100007;
    public static final int WATCH_FACE_SIGN_FAILED_ERROR_100014 = 100014;
    public static final String WATCH_FACE_SYNC_PACKAGE_HEADER_PATH = "/watchFace/watchface_sync_header.bin";
    public static final String WATCH_FACE_SYNC_PACKAGE_PATH = "/watchFace/watchface_sync.bin";
    public static final int WEAR_EXPAND_TYPE = 4;
    public static final String WEAR_PREVIEW_ROOT_PATH = "/16/";
    public static final int WEAR_RESOURCE_DOWNLOAD_ERROR = 10005;
    public static final String XML_SUFFIX = ".xml";
    public static final String ZIP_SUFFIX = ".zip";
}
