package com.huawei.healthcloud.plugintrack.model;

/* JADX INFO: loaded from: classes5.dex */
public enum SportDetailChartDataType {
    HEART_RATE,
    STEP_RATE,
    ALTITUDE,
    SPEED_RATE,
    SWOLF,
    REALTIME_PACE,
    PULL_FREQ,
    GROUND_CONTACT_TIME,
    HANG_TIME,
    GROUND_HANG_TIME_RATE,
    GROUND_IMPACT_ACCELERATION,
    JUMP_TIME,
    SPO2,
    JUMP_HEIGHT,
    POWER,
    ANALOG_POWER,
    RESISTANCE,
    PADDLE_FREQUENCY,
    CADENCE,
    ANALOG_CADENCE,
    SKIPPING_SPEED,
    HEART_RATE_RECOVERY,
    VERTICAL_OSCILLATION,
    GC_TIME_BALANCE,
    VERTICAL_RATIO,
    ACTIVE_PEAK,
    PEAK_WEIGHT
}
