4=IDS_details_sleep_content_4_no_harvard
1001=IDS_sleep_advice_1001
1002=IDS_sleep_advice_1002
1003=IDS_sleep_advice_1003
1004=IDS_sleep_advice_1004
1005=IDS_sleep_advice_1003
1006=IDS_sleep_advice_1006
1007=IDS_sleep_advice_1007
1008=IDS_sleep_advice_1008
1009=IDS_sleep_advice_1001
1010=IDS_sleep_advice_1010
2001=IDS_sleep_advice_2001
2002=IDS_sleep_advice_2002
2003=IDS_sleep_advice_2003
2004=IDS_sleep_advice_2004
2005=IDS_sleep_advice_2005
2006=IDS_sleep_advice_2006
2007=IDS_sleep_advice_2007
2008=IDS_sleep_advice_2002
2009=IDS_sleep_advice_2009
2010=IDS_sleep_advice_2010
2011=IDS_sleep_advice_2011
2012=IDS_sleep_advice_2010
2013=IDS_sleep_advice_2013
2014=IDS_sleep_advice_2014
2015=IDS_sleep_advice_2015
2016=IDS_sleep_advice_2016
2017=IDS_sleep_advice_2017
2018=IDS_sleep_advice_2018
2019=IDS_sleep_advice_2019
2020=IDS_sleep_advice_2020
2021=IDS_sleep_advice_2021
2022=IDS_sleep_advice_2022
2023=IDS_sleep_advice_2023
2024=IDS_sleep_advice_2024
2025=IDS_sleep_advice_2025
2026=IDS_sleep_advice_2026
2027=IDS_sleep_advice_2027
2028=IDS_sleep_advice_2028
2029=IDS_sleep_advice_2029
2030=IDS_sleep_advice_2030
2031=IDS_sleep_advice_2031
2032=IDS_sleep_advice_2032
2033=IDS_sleep_advice_2033
2034=IDS_sleep_advice_2034
2035=IDS_sleep_advice_2035
2036=IDS_sleep_advice_2036
2037=IDS_sleep_advice_2037
2038=IDS_sleep_advice_2038
2039=IDS_sleep_advice_2039
2040=IDS_sleep_advice_2040
2041=IDS_sleep_advice_2037
2042=IDS_sleep_advice_2042
2043=IDS_sleep_advice_2043
2044=IDS_sleep_advice_2044
2045=IDS_sleep_advice_2045
2046=IDS_sleep_advice_2046
2047=IDS_sleep_advice_2047
2048=IDS_sleep_advice_2048
2049=IDS_sleep_advice_2049
2050=IDS_sleep_advice_2050
2051=IDS_sleep_advice_2051
2052=IDS_sleep_advice_2048
2053=IDS_sleep_advice_2053
2054=IDS_sleep_advice_2054
3001=IDS_sleep_advice_3001
3002=IDS_sleep_advice_3002
3003=IDS_sleep_advice_3003
3004=IDS_sleep_advice_3004
3007=IDS_sleep_advice_3007
3008=IDS_sleep_advice_3008
3009=IDS_sleep_advice_3009
3010=IDS_sleep_advice_3010
3011=IDS_sleep_advice_3011
3012=IDS_sleep_advice_3012
3013=IDS_sleep_advice_3013
3014=IDS_sleep_advice_3014
3015=IDS_sleep_advice_3009
3016=IDS_sleep_advice_3016
3017=IDS_sleep_advice_3017
3018=IDS_sleep_advice_3018
3019=IDS_sleep_advice_3019
3020=IDS_sleep_advice_3020
3021=IDS_sleep_advice_3021
3022=IDS_sleep_advice_3022
4001=IDS_sleep_advice_4001
4002=IDS_sleep_advice_4002
4003=IDS_sleep_advice_4003
4004=IDS_sleep_advice_4004
4005=IDS_sleep_advice_4005
4006=IDS_sleep_advice_4006
4007=IDS_sleep_advice_4001
4008=IDS_sleep_advice_4008
4009=IDS_sleep_advice_4009
4010=IDS_sleep_advice_4010
4011=IDS_sleep_advice_4011
4012=IDS_sleep_advice_4012
4013=IDS_sleep_advice_4013
4014=IDS_sleep_advice_4014
4015=IDS_sleep_advice_4015
4016=IDS_sleep_advice_4004
4017=IDS_sleep_advice_4017
4018=IDS_sleep_advice_4018
4019=IDS_sleep_advice_4019
4020=IDS_sleep_advice_4020
4021=IDS_sleep_advice_4021
4022=IDS_sleep_advice_4022
4023=IDS_sleep_advice_4023
4024=IDS_sleep_advice_4024
4025=IDS_sleep_advice_4025
4026=IDS_sleep_advice_4026
4027=IDS_sleep_advice_4027
4028=IDS_sleep_advice_4028
4029=IDS_sleep_advice_4029
4030=IDS_sleep_advice_4030
4031=IDS_sleep_advice_4031
4032=IDS_sleep_advice_4032
4033=IDS_sleep_advice_4033
4034=IDS_sleep_advice_4034
4035=IDS_sleep_advice_4035
4036=IDS_sleep_advice_4036
5001=IDS_sleep_advice_5001
5002=IDS_sleep_advice_5002
5003=IDS_sleep_advice_5001
5004=IDS_sleep_advice_5004
5005=IDS_sleep_advice_5001
5006=IDS_sleep_advice_5006
5007=IDS_sleep_advice_5001
5008=IDS_sleep_advice_5008
5009=IDS_sleep_advice_5001
5010=IDS_sleep_advice_5010
5011=IDS_sleep_advice_5001
5012=IDS_sleep_advice_5012
5013=IDS_sleep_advice_5013
5014=IDS_sleep_advice_5014
5015=IDS_sleep_advice_5013
5016=IDS_sleep_advice_5016
5017=IDS_sleep_advice_5013
5018=IDS_sleep_advice_5018
5019=IDS_sleep_advice_5013
5020=IDS_sleep_advice_5020
5021=IDS_sleep_advice_5013
5022=IDS_sleep_advice_5022
5023=IDS_sleep_advice_5013
5024=IDS_sleep_advice_5024
5025=IDS_sleep_advice_5013
5026=IDS_sleep_advice_5026
5027=IDS_sleep_advice_5013
5028=IDS_sleep_advice_5028
5029=IDS_sleep_advice_5013
5030=IDS_sleep_advice_5030
5031=IDS_sleep_advice_5013
5032=IDS_sleep_advice_5032
5033=IDS_sleep_advice_5013
5034=IDS_sleep_advice_5034
6001=IDS_sleep_advice_6001
6002=IDS_sleep_advice_6002
6003=IDS_sleep_advice_6003
6004=IDS_sleep_advice_6004
6005=IDS_sleep_advice_6005
6006=IDS_sleep_advice_6006
6007=IDS_sleep_advice_6007
6008=IDS_sleep_advice_6008
6009=IDS_sleep_advice_6009
6010=IDS_sleep_advice_6010
6011=IDS_sleep_advice_6011
6012=IDS_sleep_advice_6012
6013=IDS_sleep_advice_6013
6014=IDS_sleep_advice_6014
6015=IDS_sleep_advice_6015
6016=IDS_sleep_advice_6016
6017=IDS_sleep_advice_6017
6018=IDS_sleep_advice_6018
6019=IDS_sleep_advice_6019
6020=IDS_sleep_advice_6020
6021=IDS_sleep_advice_6021
6022=IDS_sleep_advice_6022
6023=IDS_sleep_advice_6023
6024=IDS_sleep_advice_6024
6025=IDS_sleep_advice_6025
6026=IDS_sleep_advice_6026
6027=IDS_sleep_advice_6001
6028=IDS_sleep_advice_6028
7001=IDS_sleep_advice_7001
7002=IDS_sleep_advice_7002
7003=IDS_sleep_advice_7003
7004=IDS_sleep_advice_7004
7005=IDS_sleep_advice_7001
7006=IDS_sleep_advice_7006
7007=IDS_sleep_advice_7007
7008=IDS_sleep_advice_7008
7009=IDS_sleep_advice_7009
7010=IDS_sleep_advice_7010
7011=IDS_sleep_advice_7011
7012=IDS_sleep_advice_7012
7013=IDS_sleep_advice_7013
7014=IDS_sleep_advice_7014
7015=IDS_sleep_advice_7015
7016=IDS_sleep_advice_7016
7017=IDS_sleep_advice_7017
7018=IDS_sleep_advice_7018
7019=IDS_sleep_advice_7019
7020=IDS_sleep_advice_7020
7021=IDS_sleep_advice_7021
7022=IDS_sleep_advice_7022
7023=IDS_sleep_advice_7023
7024=IDS_sleep_advice_7024
10001=IDS_sleep_advice_10001
10002=IDS_sleep_advice_10002
10003=IDS_sleep_advice_10003
10004=IDS_sleep_advice_10004
12001=IDS_hw_core_sleep_advice_less_sleep_days_id_12001
12101=IDS_hw_core_sleep_advice_very_good_id_12101
12102=IDS_hw_core_sleep_advice_very_good_id_12102
13102=IDS_hw_core_sleep_advice_very_good_id_13102
12103=IDS_hw_core_sleep_advice_very_good_id_12103
13103=IDS_hw_core_sleep_advice_very_good_id_13103
12104=IDS_hw_core_sleep_advice_very_good_id_12104
13104=IDS_hw_core_sleep_advice_very_good_id_13104
12201=IDS_hw_core_sleep_advice_bad_all_sleep_id_12201
13201=IDS_hw_core_sleep_advice_bad_all_sleep_id_13201
12202=IDS_hw_core_sleep_advice_bad_all_sleep_id_12201
13202=IDS_hw_core_sleep_advice_bad_all_sleep_id_13201
12203=IDS_hw_core_sleep_advice_bad_all_sleep_id_12203
13203=IDS_hw_core_sleep_advice_bad_all_sleep_id_13203
12204=IDS_hw_core_sleep_advice_bad_all_sleep_id_12203
13204=IDS_hw_core_sleep_advice_bad_all_sleep_id_13203
12205=IDS_hw_core_sleep_advice_bad_all_sleep_id_12205_new
13205=IDS_hw_core_sleep_advice_bad_all_sleep_id_13205_new
12206=IDS_hw_core_sleep_advice_bad_all_sleep_id_12205_new
13206=IDS_hw_core_sleep_advice_bad_all_sleep_id_13205_new
12207=IDS_hw_core_sleep_advice_bad_all_sleep_id_12207
13207=IDS_hw_core_sleep_advice_bad_all_sleep_id_13207
12208=IDS_hw_core_sleep_advice_bad_all_sleep_id_12208
13208=IDS_hw_core_sleep_advice_bad_all_sleep_id_13208
12209=IDS_hw_core_sleep_advice_bad_all_sleep_id_12209
13209=IDS_hw_core_sleep_advice_bad_all_sleep_id_13209
12210=IDS_hw_core_sleep_advice_bad_all_sleep_id_12210
13210=IDS_hw_core_sleep_advice_bad_all_sleep_id_13210
12211=IDS_hw_core_sleep_advice_bad_all_sleep_id_12211
13211=IDS_hw_core_sleep_advice_bad_all_sleep_id_13211
12212=IDS_hw_core_sleep_advice_bad_all_sleep_id_12212
13212=IDS_hw_core_sleep_advice_bad_all_sleep_id_13212
12213=IDS_hw_core_sleep_advice_bad_all_sleep_id_12213
13213=IDS_hw_core_sleep_advice_bad_all_sleep_id_13213
12301=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12301_new
13301=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13301_new
12302=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12301_new
13302=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13301_new
12303=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12301_new
13303=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13301_new
12304=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12304_new
13304=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13304_new
12305=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12304_new
13305=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13304_new
12306=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12304_new
13306=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13304_new
12307=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12307_new
13307=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13307_new
12308=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12308_new
13308=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13308_new
12309=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12309
13309=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13309
12310=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12310_new
13310=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13310_new
12311=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12311_new
13311=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13311_new
12312=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12312_new
13312=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13312_new
12401=IDS_hw_core_sleep_advice_low_RDI_id_12401
13401=IDS_hw_core_sleep_advice_low_RDI_id_13401
12402=IDS_hw_core_sleep_advice_low_RDI_id_12401
13402=IDS_hw_core_sleep_advice_low_RDI_id_13401
12403=IDS_hw_core_sleep_advice_low_RDI_id_12401
13403=IDS_hw_core_sleep_advice_low_RDI_id_13401
12404=IDS_hw_core_sleep_advice_low_RDI_id_12404
13404=IDS_hw_core_sleep_advice_low_RDI_id_13404
12405=IDS_hw_core_sleep_advice_low_RDI_id_12404
13405=IDS_hw_core_sleep_advice_low_RDI_id_13404
12406=IDS_hw_core_sleep_advice_low_RDI_id_12406
13406=IDS_hw_core_sleep_advice_low_RDI_id_13406
12407=IDS_hw_core_sleep_advice_low_RDI_id_12407
13407=IDS_hw_core_sleep_advice_low_RDI_id_13407
12408=IDS_hw_core_sleep_advice_low_RDI_id_12408
13408=IDS_hw_core_sleep_advice_low_RDI_id_13408
12501=IDS_hw_core_sleep_advice_bad_REM_id_12501
13501=IDS_hw_core_sleep_advice_bad_REM_id_13501
12502=IDS_hw_core_sleep_advice_bad_REM_id_12502
13502=IDS_hw_core_sleep_advice_bad_REM_id_13502
12503=IDS_hw_core_sleep_advice_bad_REM_id_12503
13503=IDS_hw_core_sleep_advice_bad_REM_id_13503
12504=IDS_hw_core_sleep_advice_bad_REM_id_12503
13504=IDS_hw_core_sleep_advice_bad_REM_id_13503
12505=IDS_hw_core_sleep_advice_bad_REM_id_12505
13505=IDS_hw_core_sleep_advice_bad_REM_id_13505
12506=IDS_hw_core_sleep_advice_bad_REM_id_12505
13506=IDS_hw_core_sleep_advice_bad_REM_id_13505
12507=IDS_hw_core_sleep_advice_bad_REM_id_12507
13507=IDS_hw_core_sleep_advice_bad_REM_id_13507
12601=IDS_hw_core_sleep_advice_irregular_id_12601
13601=IDS_hw_core_sleep_advice_irregular_id_13601
12602=IDS_hw_core_sleep_advice_irregular_id_12602
13602=IDS_hw_core_sleep_advice_irregular_id_13602
12603=IDS_hw_core_sleep_advice_irregular_id_12603
13603=IDS_hw_core_sleep_advice_irregular_id_13603
12604=IDS_hw_core_sleep_advice_irregular_id_12603
13604=IDS_hw_core_sleep_advice_irregular_id_13603
12605=IDS_hw_core_sleep_advice_irregular_id_12605
13605=IDS_hw_core_sleep_advice_irregular_id_13605
12606=IDS_hw_core_sleep_advice_irregular_id_12606
13606=IDS_hw_core_sleep_advice_irregular_id_13606
12607=IDS_hw_core_sleep_advice_irregular_id_12607
13607=IDS_hw_core_sleep_advice_irregular_id_13607
12608=IDS_hw_core_sleep_advice_irregular_id_12608
13608=IDS_hw_core_sleep_advice_irregular_id_13608
12609=IDS_hw_core_sleep_advice_irregular_id_12609
13609=IDS_hw_core_sleep_advice_irregular_id_13609
12610=IDS_hw_core_sleep_advice_irregular_id_12610
13610=IDS_hw_core_sleep_advice_irregular_id_13610
12611=IDS_hw_core_sleep_advice_irregular_id_12611
13611=IDS_hw_core_sleep_advice_irregular_id_13611
12701=IDS_hw_core_sleep_advice_large_vary_id_12701
13701=IDS_hw_core_sleep_advice_large_vary_id_13701
12702=IDS_hw_core_sleep_advice_large_vary_id_12702
13702=IDS_hw_core_sleep_advice_large_vary_id_13702
12703=IDS_hw_core_sleep_advice_large_vary_id_12702
13703=IDS_hw_core_sleep_advice_large_vary_id_13702
12704=IDS_hw_core_sleep_advice_large_vary_id_12704
13704=IDS_hw_core_sleep_advice_large_vary_id_13704
12705=IDS_hw_core_sleep_advice_large_vary_id_12705
13705=IDS_hw_core_sleep_advice_large_vary_id_13705
12706=IDS_hw_core_sleep_advice_large_vary_id_12705
13706=IDS_hw_core_sleep_advice_large_vary_id_13705
12801=IDS_hw_core_sleep_advice_qulity_id_12801
13801=IDS_hw_core_sleep_advice_qulity_id_13801
12802=IDS_hw_core_sleep_advice_qulity_id_12802
13802=IDS_hw_core_sleep_advice_qulity_id_13802
12803=IDS_hw_core_sleep_advice_qulity_id_12803
13803=IDS_hw_core_sleep_advice_qulity_id_13803
12804=IDS_hw_core_sleep_advice_qulity_id_12804
13804=IDS_hw_core_sleep_advice_qulity_id_13804
12805=IDS_hw_core_sleep_advice_qulity_id_12805
13805=IDS_hw_core_sleep_advice_qulity_id_13805
12806=IDS_hw_core_sleep_advice_qulity_id_12806
13806=IDS_hw_core_sleep_advice_qulity_id_13806
12807=IDS_hw_core_sleep_advice_qulity_id_12807
13807=IDS_hw_core_sleep_advice_qulity_id_13807
12808=IDS_hw_core_sleep_advice_qulity_id_12808
13808=IDS_hw_core_sleep_advice_qulity_id_13808
12809=IDS_hw_core_sleep_advice_qulity_id_12808
13809=IDS_hw_core_sleep_advice_qulity_id_13808
12810=IDS_hw_core_sleep_advice_qulity_id_12808
13810=IDS_hw_core_sleep_advice_qulity_id_13808
12811=IDS_hw_core_sleep_advice_qulity_id_12811
13811=IDS_hw_core_sleep_advice_qulity_id_13811
12812=IDS_hw_core_sleep_advice_qulity_id_12811
13812=IDS_hw_core_sleep_advice_qulity_id_13811
12813=IDS_hw_core_sleep_advice_qulity_id_12813
13813=IDS_hw_core_sleep_advice_qulity_id_13813
12814=IDS_hw_core_sleep_advice_qulity_id_12813
13814=IDS_hw_core_sleep_advice_qulity_id_13813
12815=IDS_hw_core_sleep_advice_qulity_id_12815
13815=IDS_hw_core_sleep_advice_qulity_id_13815
14301=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14301
14302=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14301
14303=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14301
15301=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15301
15302=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15301
15303=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15301
14304=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14304
14305=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14304
14306=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14304
15304=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15304
15305=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15304
15306=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15304
14307=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14307
15307=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15307
14308=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14308
15308=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15308
14309=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14309
15309=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15309
14310=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14310
14311=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14311
15310=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15310
15311=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15311
14312=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14312
15312=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15312
14801=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14801
15801=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15801
14805=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14805
15805=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15805
14806=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14806
15806=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15806
14807=IDS_hw_core_sleep_advice_lack_deep_sleep_id_14807
15807=IDS_hw_core_sleep_advice_lack_deep_sleep_id_15807
12901=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12901
12902=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12901
12903=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12901
13901=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13901
13902=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13901
13903=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13901
12904=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12904
12905=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12904
12906=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12904
13904=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13904
13905=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13904
13906=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13904
12907=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12907
13907=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13907
12908=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12908
13908=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13908
12909=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12909
13909=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13909
12910=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12910
13910=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13910
12911=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12911
13911=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13911
12912=IDS_hw_core_sleep_advice_lack_deep_sleep_id_12912
13912=IDS_hw_core_sleep_advice_lack_deep_sleep_id_13912